# infra/docker/Dockerfile.server
FROM node:20-alpine AS build

WORKDIR /app
COPY package*.json ./
RUN npm ci

COPY . .
RUN npm run build
RUN npm run build:server

FROM node:20-alpine AS runtime
WORKDIR /app

ENV NODE_ENV=production
COPY package*.json ./
RUN npm ci --omit=dev

COPY --from=build /app/dist /app/dist
COPY --from=build /app/dist-server /app/dist-server

ENV PORT=4000
CMD ["node", "dist-server/server/index.js"]
