FROM gradle:9.0-jdk17 AS builder

WORKDIR /workspace
COPY decision-engine/ /workspace

USER root
RUN chmod +x gradlew
RUN chown -R gradle:gradle /workspace
USER gradle
RUN ./gradlew --no-daemon bootJar -x test

FROM eclipse-temurin:17-jre
WORKDIR /app

COPY --from=builder /workspace/build/libs/*.jar ./decision-engine.jar

EXPOSE 8080
ENTRYPOINT ["java", "-jar", "/app/decision-engine.jar"]
