name: Feature request
description: Suggest an idea to make the app better
labels: [enhancement]
body:
  - type: textarea
    attributes:
      label: Problem statement
      description: What problem would this feature solve?
    validations:
      required: true
  - type: textarea
    attributes:
      label: Proposed solution
  - type: textarea
    attributes:
      label: Alternatives considered