apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - namespaces.yaml
  - config.yaml
  - postgres.yaml
  - backend.yaml
  - ml-service.yaml
  - ingress.yaml
  - tls.yaml
  - observability.yaml
  - bi.yaml
