apiVersion: v1
kind: Namespace
metadata:
  name: dd-app
  labels:
    app.kubernetes.io/name: dd-app
    app.kubernetes.io/part-of: dd-decider
---
apiVersion: v1
kind: Namespace
metadata:
  name: dd-observability
  labels:
    app.kubernetes.io/name: dd-observability
    app.kubernetes.io/part-of: dd-decider
